### ISSUE TITLE
NPM Error with TextDecoder

### ISSUE THREAD

**Issue by xXLokerXx** [kataras/neffos.js#5]
Im working with npm and i install neffos affter the update you do for #4 the library send me an error: `ReferenceError: TextDecoder is not defined` i don't know why is this happend, but i add this correction to and works (for me at least) :

```js
var encoding = require('text-encoding');
var textDecoder = new encoding.TextDecoder("utf-8");
```

this is on lines 248 of `neffos.js` file.

@kataras would you think this change could be upload whitout any issues? and could you update to this works on npm usage?

**Comment by kataras** [comment]
Seems that Text Encoder is a browser-only feature, in nodejs it requires the text-encoding package, you have absoltue right @xXLokerXx.
